name: moelholm.com
title: moelholm.com
url: https://moelholm.com
google_analytics: UA-7400692-1
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
    line_numbers: true
plugins:
  - jekyll-sitemap    