name: moelholm.com
title: moelholm.com
url: https://moelholm.com
google_analytics: UA-7400692-1
markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false  
    block:
      line_numbers: true
collections:
  running:
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title
    tags: true
  software_engineering:
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title
    tags: true
plugins:
  - jekyll-sitemap