# Local development configuration
# This file extends _config.yml with development-specific settings

# Enable unpublished posts for local development (published: false)
unpublished: true

# Also include future-dated posts
future: true

# Development-specific settings
host: 0.0.0.0
port: 4000
livereload: true
incremental: false

# Optional: Different base URL for local development
# baseurl: ""
