name: Auto-merge toot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Check label and merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          pr_number=${{ github.event.pull_request.number }}
          # If the PR doesn't have the 'toots' label, exit quietly
          if ! gh pr view "$pr_number" --repo "$REPO" --json labels --jq '.labels[].name' | grep -qx toots; then
            echo "PR #$pr_number has no 'toots' label; skipping."
            exit 0
          fi
          # Try squash merge, allow auto-merge if branch protection requires checks
          gh pr merge "$pr_number" --repo "$REPO" --squash --auto --delete-branch || gh pr merge "$pr_number" --repo "$REPO" --squash --delete-branch