name: fetch-toots

on:
  schedule:
  - cron: '*/10 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: fetch-toots
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Mastodon toots (composite)
        uses: ./.github/actions/fetch-collection
        with:
          script: tools/fetch_toots.py
          collection_dir: site/blog_collections/_toots
          assets_dir: site/assets/toots_media
          pr_branch: bot/mastodon-toots
          pr_title: Refresh toot files
          pr_body: Automated update of Mastodon toot files.
          pr_label: toots
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_INSTANCE: ${{ vars.MASTODON_INSTANCE }}
          MASTODON_USER_ID: ${{ secrets.MASTODON_USER_ID }}
          MASTODON_TAGS: running,ultrarunning,trailrunning,strengthtraining
          MASTODON_LIMIT: 10
          MASTODON_MODE: global
