name: Build & Deploy (Jekyll / GitHub Pages)

on:
  push:
    branches: [ master ]
  # Ensure Pages deploys after automated toot PR merges, since pushes from
  # GITHUB_TOKEN won't trigger workflows. This runs when the auto-merge workflow completes.
  workflow_run:
    workflows: ["Auto-merge toot PRs"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # For workflow_run, only proceed when the upstream workflow succeeded on master
    if: github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Jekyll (from subfolder)
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./site
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
